routes/web.php
//SubCounties routes .....

Route::resource('admin/subcounties','admin\SubCountiesController');

Route::get('/admin/subcountiesreport', 'admin\SubCountiesController@report');

Route::post('/admin/subcountiesfilter', 'admin\SubCountiesController@filter');
Route::post('/admin/getsubcounties', 'admin\SubCountiesController@getSubCountiesByCounty');

//Branches routes .....

Route::resource('admin/branches','admin\BranchesController');

Route::get('/admin/branchesreport', 'admin\BranchesController@report');

Route::post('/admin/branchesfilter', 'admin\BranchesController@filter');

//BankingModes routes .....

Route::resource('admin/bankingmodes','admin\BankingModesController');

Route::get('/admin/bankingmodesreport', 'admin\BankingModesController@report');

Route::post('/admin/bankingmodesfilter', 'admin\BankingModesController@filter');

//ManagesDepartmentsData routes .....

Route::resource('admin/managesdepartmentsdata','admin\ManagesDepartmentsDataController');

Route::get('/admin/managesdepartmentsdatareport', 'admin\ManagesDepartmentsDataController@report');

Route::post('/admin/managesdepartmentsdatafilter', 'admin\ManagesDepartmentsDataController@filter');

//Departments routes .....

Route::resource('admin/departments','admin\DepartmentsController');

Route::get('/admin/departmentsreport', 'admin\DepartmentsController@report');

Route::post('/admin/departmentsfilter', 'admin\DepartmentsController@filter');

//Departments routes .....

Route::resource('admin/departments','admin\DepartmentsController');

Route::get('/admin/departmentsreport', 'admin\DepartmentsController@report');

Route::post('/admin/departmentsfilter', 'admin\DepartmentsController@filter');

//Departments routes .....

Route::resource('admin/departments','admin\DepartmentsController');

Route::get('/admin/departmentsreport', 'admin\DepartmentsController@report');

Route::post('/admin/departmentsfilter', 'admin\DepartmentsController@filter');

//EmployeeCategories routes .....

Route::resource('admin/employeecategories','admin\EmployeeCategoriesController');

Route::get('/admin/employeecategoriesreport', 'admin\EmployeeCategoriesController@report');

Route::post('/admin/employeecategoriesfilter', 'admin\EmployeeCategoriesController@filter');

//EmployeeGroups routes .....

Route::resource('admin/employeegroups','admin\EmployeeGroupsController');

Route::get('/admin/employeegroupsreport', 'admin\EmployeeGroupsController@report');

Route::post('/admin/employeegroupsfilter', 'admin\EmployeeGroupsController@filter');
Route::get('/admin/groupsimport','admin\GroupsController@dbimport');

//PayFrequencies routes .....

Route::resource('admin/payfrequencies','admin\PayFrequenciesController');

Route::get('/admin/payfrequenciesreport', 'admin\PayFrequenciesController@report');

Route::post('/admin/payfrequenciesfilter', 'admin\PayFrequenciesController@filter');

//PayModes routes .....

Route::resource('admin/paymodes','admin\PayModesController');

Route::get('/admin/paymodesreport', 'admin\PayModesController@report');

Route::post('/admin/paymodesfilter', 'admin\PayModesController@filter');

//PayPoints routes .....

Route::resource('admin/paypoints','admin\PayPointsController');

Route::get('/admin/paypointsreport', 'admin\PayPointsController@report');

Route::post('/admin/paypointsfilter', 'admin\PayPointsController@filter');

//MaritalStatuses routes .....

Route::resource('admin/maritalstatuses','admin\MaritalStatusesController');

Route::get('/admin/maritalstatusesreport', 'admin\MaritalStatusesController@report');

Route::post('/admin/maritalstatusesfilter', 'admin\MaritalStatusesController@filter');

Route::get('/admin/getmaritalstatus/{id}', 'admin\MaritalStatusesController@getmaritalstatus');

//Banks routes .....

Route::resource('admin/banks','admin\BanksController');

Route::get('/admin/banksreport', 'admin\BanksController@report');

Route::post('/admin/banksfilter', 'admin\BanksController@filter');

//BankBranches routes .....

Route::resource('admin/bankbranches','admin\BankBranchesController');

Route::get('/admin/bankbranchesreport', 'admin\BankBranchesController@report');

Route::post('/admin/bankbranchesfilter', 'admin\BankBranchesController@filter');

//Positions routes .....

Route::resource('admin/positions','admin\PositionsController');

Route::get('/admin/positionsreport', 'admin\PositionsController@report');

Route::post('/admin/positionsfilter', 'admin\PositionsController@filter');

//Employees routes .....

Route::resource('admin/employees','admin\EmployeesController');

Route::get('/admin/employeesreport', 'admin\EmployeesController@report');
Route::get('/admin/employeesimport', 'admin\EmployeesController@dbimport');

Route::post('/admin/employeesfilter', 'admin\EmployeesController@filter');
Route::post('/admin/employeescount', 'admin\EmployeesController@employeesCount');

//Clients routes .....

Route::resource('admin/clients','admin\ClientsController');

Route::get('/admin/clientsreport', 'admin\ClientsController@report');

Route::get('/admin/importfromdb', 'admin\ClientsController@importfromdb');

Route::post('/admin/dbimport', 'admin\ClientsImportController@dbimport');

Route::post('/admin/clientsfilter', 'admin\ClientsController@filter');

Route::post('/admin/clientscount', 'admin\ClientsController@clientsCount');

Route::get('/admin/clientssearch', 'admin\ClientsController@clientssearch');

Route::post('/admin/searchclient', 'admin\ClientsController@searchclient');

Route::get('/admin/clientapproval/{id}', 'admin\ClientsController@clientapproval');
Route::get('/admin/clientremoval/{id}', 'admin\ClientsController@clientremoval');
Route::get('/admin/clientblacklisting/{id}', 'admin\ClientsController@clientblacklisting');
Route::get('/admin/clientsuspension/{id}', 'admin\ClientsController@clientsuspension');
Route::get('/admin/clientgroupchange/{id}', 'admin\ClientsController@clientgroupchange');
Route::post('/admin/changeclientgroup/{id}', 'admin\ClientsController@changeclientgroup');
Route::get('/admin/clienttypechange/{id}/{code}', 'admin\ClientsController@clienttypechange');
Route::post('/admin/changeclienttype/{id}/{code}', 'admin\ClientsController@changeclienttype');
Route::post('/admin/getclients', 'admin\ClientsController@getclients');

Route::post('/admin/approveclient/{id}', 'admin\ClientsController@approveclient');
Route::post('/admin/blacklistclient/{id}', 'admin\ClientsController@blacklistclient');
Route::post('/admin/removeclient/{id}', 'admin\ClientsController@removeclient');
Route::post('/admin/suspendclient/{id}', 'admin\ClientsController@suspendclient');

// Client Query routes .....

Route::post('admin/client/query','admin\ClientsController@query')->name('client.query');
Route::post('admin/client/query2','admin\ClientsController@query2')->name('client.query2');
Route::post('admin/client/contribute','admin\ClientsController@contribute')->name('client.contribute');

Route::post('admin/client/individualize/{client}','admin\ClientsController@individualize')->name('client.individualize');

//Days routes .....


Route::resource('admin/days','admin\DaysController');

Route::get('/admin/daysreport', 'admin\DaysController@report');

Route::post('/admin/daysfilter', 'admin\DaysController@filter');

//MeetingFrequencies routes .....

Route::resource('admin/meetingfrequencies','admin\MeetingFrequenciesController');

Route::get('/admin/meetingfrequenciesreport', 'admin\MeetingFrequenciesController@report');

Route::post('/admin/meetingfrequenciesfilter', 'admin\MeetingFrequenciesController@filter');

//Groups routes .....

Route::resource('admin/groups','admin\GroupsController');
Route::post('/admin/groups/customize/{groups}', 'admin\GroupsController@customize')->name('groups.customize');

Route::resource('admin/groups/leadership/category','GroupLeadershipCategoryController', ['as' => 'groups.leadership']);
Route::resource('admin/groups/leadership/catalog','GroupLeadershipController', ['as' => 'groups.leadership']);

Route::get('/admin/groupsreport', 'admin\GroupsController@report');

Route::post('/admin/groupsfilter', 'admin\GroupsController@filter');
Route::post('/admin/groupscount', 'admin\GroupsController@groupsCount');

Route::resource('admin/groupcontributions','admin\GroupContributionsController');

Route::get('admin/groupcontributions/receipt/{id}','admin\GroupContributionsController@receipt');

Route::resource('admin/ptrreport','admin\PTRReportController');
Route::get('admin/ptrreport/{id}/export','admin\PTRReportController@export')->name('ptrreport.export');;

//GroupRoles routes .....

Route::resource('admin/grouproles','admin\GroupRolesController');

Route::get('/admin/grouprolesreport', 'admin\GroupRolesController@report');

Route::post('/admin/grouprolesfilter', 'admin\GroupRolesController@filter');

//GroupClients routes .....

Route::resource('admin/groupclients','admin\GroupClientsController');

Route::get('/admin/groupclientsreport', 'admin\GroupClientsController@report');

Route::get('/admin/groupclientsdbimport', 'admin\GroupClientsController@dbimport');

Route::post('/admin/groupclientsfilter', 'admin\GroupClientsController@filter');

//GroupClientRoles routes .....

Route::resource('admin/groupclientroles','admin\GroupClientRolesController');

Route::get('/admin/groupclientrolesreport', 'admin\GroupClientRolesController@report');

Route::post('/admin/groupclientrolesfilter', 'admin\GroupClientRolesController@filter');

//TransactionStatuses routes .....

Route::resource('admin/transactionstatuses','admin\TransactionStatusesController');

Route::get('/admin/transactionstatusesreport', 'admin\TransactionStatusesController@report');

Route::post('/admin/transactionstatusesfilter', 'admin\TransactionStatusesController@filter');

//FinancialCategories routes .....

Route::resource('admin/financialcategories','admin\FinancialCategoriesController');

Route::get('/admin/financialcategoriesreport', 'admin\FinancialCategoriesController@report');

app/Http/Controllers/admin/MaritalStatusesController.php
<?php
namespace App\Http\Controllers\admin;
use Illuminate\Http\Request;
use App\Http\Requests;
use App\MaritalStatuses;
use App\Companies;
use App\Modules;
use App\Users;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use App\UsersAccountsRoles;
class MaritalStatusesController extends Controller
{

	public function __construct(){
		$this->middleware('auth');
	}
	public function index(){
		$maritalstatusesdata['list']=MaritalStatuses::all();
		$user=Users::where([['id','=',Auth::id()]])->get();
		$module=Modules::where([['name','=','MaritalStatuses']])->get();
		$maritalstatusesdata['usersaccountsroles']=UsersAccountsRoles::where([['user_account','=',$user[0]['user_account']],['module','=',$module[0]['id']]])->get();
		if($maritalstatusesdata['usersaccountsroles'][0]['_add']==0&&$maritalstatusesdata['usersaccountsroles'][0]['_list']==0&&$maritalstatusesdata['usersaccountsroles'][0]['_edit']==0&&$maritalstatusesdata['usersaccountsroles'][0]['_edit']==0&&$maritalstatusesdata['usersaccountsroles'][0]['_show']==0&&$maritalstatusesdata['usersaccountsroles'][0]['_delete']==0&&$maritalstatusesdata['usersaccountsroles'][0]['_report']==0){
			return view('admin.error.denied',compact('maritalstatusesdata'));
		}else{
			return view('admin.marital_statuses.index',compact('maritalstatusesdata'));
		}
	}

	public function create(){
		$maritalstatusesdata;
		$user=Users::where([['id','=',Auth::id()]])->get();
		$module=Modules::where([['name','=','MaritalStatuses']])->get();
		$maritalstatusesdata['usersaccountsroles']=UsersAccountsRoles::where([['user_account','=',$user[0]['user_account']],['module','=',$module[0]['id']]])->get();
		if($maritalstatusesdata['usersaccountsroles'][0]['_add']==0){
			return view('admin.error.denied',compact('maritalstatusesdata'));
		}else{
			return view('admin.marital_statuses.create',compact('maritalstatusesdata'));
		}
	}

	public function filter(Request $request){
		$maritalstatusesdata['list']=MaritalStatuses::where([['code','LIKE','%'.$request->get('code').'%'],['name','LIKE','%'.$request->get('name').'%'],])->get();
		$user=Users::where([['id','=',Auth::id()]])->get();
		$module=Modules::where([['name','=','MaritalStatuses']])->get();
		$maritalstatusesdata['usersaccountsroles']=UsersAccountsRoles::where([['user_account','=',$user[0]['user_account']],['module','=',$module[0]['id']]])->get();
		if($maritalstatusesdata['usersaccountsroles'][0]['_add']==0&&$maritalstatusesdata['usersaccountsroles'][0]['_list']==0&&$maritalstatusesdata['usersaccountsroles'][0]['_edit']==0&&$maritalstatusesdata['usersaccountsroles'][0]['_edit']==0&&$maritalstatusesdata['usersaccountsroles'][0]['_show']==0&&$maritalstatusesdata['usersaccountsroles'][0]['_delete']==0&&$maritalstatusesdata['usersaccountsroles'][0]['_report']==0){
			return view('admin.error.denied',compact('maritalstatusesdata'));
		}else{
			return view('admin.marital_statuses.index',compact('maritalstatusesdata'));
		}
	}

	public function report(){
		$maritalstatusesdata['company']=Companies::all();
		$maritalstatusesdata['list']=MaritalStatuses::all();
		$user=Users::where([['id','=',Auth::id()]])->get();
		$module=Modules::where([['name','=','MaritalStatuses']])->get();
		$maritalstatusesdata['usersaccountsroles']=UsersAccountsRoles::where([['user_account','=',$user[0]['user_account']],['module','=',$module[0]['id']]])->get();
		if($maritalstatusesdata['usersaccountsroles'][0]['_report']==0){
			return view('admin.error.denied',compact('maritalstatusesdata'));
		}else{
			return view('admin.marital_statuses.report',compact('maritalstatusesdata'));
		}
	}

	public function chart(){
		return view('admin.marital_statuses.chart');
	}

	public function store(Request $request){
		$maritalstatuses=new MaritalStatuses();
		$maritalstatuses->code=$request->get('code');
		$maritalstatuses->name=$request->get('name');
		$response=array();
		$user=Users::where([['id','=',Auth::id()]])->get();
		$module=Modules::where([['name','=','MaritalStatuses']])->get();
		$maritalstatusesdata['usersaccountsroles']=UsersAccountsRoles::where([['user_account','=',$user[0]['user_account']],['module','=',$module[0]['id']]])->get();
		if($maritalstatusesdata['usersaccountsroles'][0]['_show']==1){
			try{
				if($maritalstatuses->save()){
					$response['status']='1';
					$response['message']='marital statuses Added successfully';
					return json_encode($response);
			}else{
					$response['status']='0';
					$response['message']='Failed to add marital statuses. Please try again';
					return json_encode($response);
				}
			}
			catch(Exception $e){
					$response['status']='0';
					$response['message']='An Error occured while attempting to add marital statuses. Please try again';
					return json_encode($response);
			}
		}else{
			$response['status']='0';
			$response['message']='Access Denied!';
			return json_encode($response);
		}
	}

	public function edit($id){
		$maritalstatusesdata['data']=MaritalStatuses::find($id);
		$user=Users::where([['id','=',Auth::id()]])->get();
		$module=Modules::where([['name','=','MaritalStatuses']])->get();
		$maritalstatusesdata['usersaccountsroles']=UsersAccountsRoles::where([['user_account','=',$user[0]['user_account']],['module','=',$module[0]['id']]])->get();
		if($maritalstatusesdata['usersaccountsroles'][0]['_edit']==0){
			return view('admin.error.denied',compact('maritalstatusesdata'));
		}else{
		return view('admin.marital_statuses.edit',compact('maritalstatusesdata','id'));
		}
	}

	public function show($id){
		$maritalstatusesdata['data']=MaritalStatuses::find($id);
		$user=Users::where([['id','=',Auth::id()]])->get();
		$module=Modules::where([['name','=','MaritalStatuses']])->get();
		$maritalstatusesdata['usersaccountsroles']=UsersAccountsRoles::where([['user_account','=',$user[0]['user_account']],['module','=',$module[0]['id']]])->get();
		if($maritalstatusesdata['usersaccountsroles'][0]['_show']==0){
			return view('admin.error.denied',compact('maritalstatusesdata'));
		}else{
		return view('admin.marital_statuses.show',compact('maritalstatusesdata','id'));
		}
	}

	public function getmaritalstatus($id){
		$maritalstatusesdata=MaritalStatuses::find($id);
		return json_encode($maritalstatusesdata);
	}


	public function update(Request $request,$id){
		$maritalstatuses=MaritalStatuses::find($id);
		$maritalstatuses->code=$request->get('code');
		$maritalstatuses->name=$request->get('name');
		$user=Users::where([['id','=',Auth::id()]])->get();
		$module=Modules::where([['name','=','MaritalStatuses']])->get();
		$maritalstatusesdata['usersaccountsroles']=UsersAccountsRoles::where([['user_account','=',$user[0]['user_account']],['module','=',$module[0]['id']]])->get();
		if($maritalstatusesdata['usersaccountsroles'][0]['_edit']==0){
			return view('admin.error.denied',compact('maritalstatusesdata'));
		}else{
		$maritalstatuses->save();
		$maritalstatusesdata['data']=MaritalStatuses::find($id);
		return view('admin.marital_statuses.edit',compact('maritalstatusesdata','id'));
		}
	}

	public function destroy($id){
		$maritalstatuses=MaritalStatuses::find($id);
		$user=Users::where([['id','=',Auth::id()]])->get();
		$module=Modules::where([['name','=','MaritalStatuses']])->get();
		$maritalstatusesdata['usersaccountsroles']=UsersAccountsRoles::where([['user_account','=',$user[0]['user_account']],['module','=',$module[0]['id']]])->get();
		if($maritalstatusesdata['usersaccountsroles'][0]['_delete']==1){
			$maritalstatuses->delete();
		}return redirect('admin/maritalstatuses')->with('success','marital statuses has been deleted!');
	}
}

resources/views/admin/marital_statuses/create.blade.php
@extends("admin.home")
@section("main_content")
<div id="content" class="content">
    <ol class="breadcrumb pull-right">
        <li><a href="#">Home</a></li>
        <li><a href="#">public</a></li>
        <li><a href="#">Marital Statuses</a></li>
        <li class="active">form</li>
    </ol>
    <h1 class="page-header">Marital Statuses Form <small>marital statuses details goes here...</small></h1>
    <div class="row">
        <div class="col-md-12">
            <a href="{!! route('maritalstatuses.index') !!}"><button type="button" class="btn btn-inverse btn-icon btn-circle m-b-10"><i class="fa fa-arrow-left"></i></button></a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-inverse">
                <div class="panel-heading">
                    <div class="panel-heading-btn">
                        <a href="#" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                        <a href="#" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
                        <a href="#" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                        <a href="#" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                    </div>
                    <h4 class="panel-title">DataForm - Autofill</h4>
                </div>
                <div class="panel-body">
                    <form id="form"  class="form-horizontal" enctype="multipart/form-data">
                        {!! csrf_field() !!}
                                <div class="form-group">
                                    <label for="Code" class="col-sm-3 control-label">Code</label>
                                    <div class="col-sm-6">
                                        <input type="text" name="code"  id="code" class="form-control" placeholder="Code" value="">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="Name" class="col-sm-3 control-label">Name</label>
                                    <div class="col-sm-6">
                                        <input type="text" name="name"  id="name" class="form-control" placeholder="Name" value="">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-sm-offset-3 col-sm-6">
                                        <button type="button" onclick="save()" class="btn btn-sm btn-primary">
                                            <i class="fa fa-btn fa-plus"></i> Add Marital Statuses
                                        </button>
                                    </div>
                                </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script language="javascript" type="text/javascript">
function save(){
	var formData = new FormData($('#form')[0]);
	$.ajax({
		type:'POST',
		url: "{!! route('maritalstatuses.store')!!}",
		data:formData,
		cache:false,
		contentType: false,
		processData: false,
		success:function(data){
			var obj = jQuery.parseJSON( data );
			if(obj.status=='1'){
				$.gritter.add({
					title: 'Success',
					text: obj.message,
					sticky: false,
					time: '1000',
				});
				$("#form")[0].reset();
			}else{
				$.gritter.add({
					title: 'Fail',
					text: obj.message,
					sticky: false,
					time: '5000',
				});
			}
		},error: function(data){
console.log(data)
			$.gritter.add({
				title: 'Error',
				text: 'An Error occured. Please review your data then submit again!!',
				sticky: false,
				time: '5000',
			});
		}
	});
	return false;
}
</script>
@endsection
@section('script')
@endsection

resources/views/admin/marital_statuses/index.blade.php
@extends("admin.home")
@section("main_content")
<div id="content" class="content">
    <ol class="breadcrumb pull-right">
        <li><a href="#">Home</a></li>
        <li><a href="#">Public</a></li>
        <li><a href="#">Marital Statuses</a></li>
        <li class="active">Table</li>
    </ol>
    <h1 class="page-header">Marital Statuses - DATA <small>marital statuses data goes here...</small></h1>
    <div class="row">
        <div class="col-md-12">
            @if($maritalstatusesdata['usersaccountsroles'][0]->_add==1)
            <a href="{!! route('maritalstatuses.create') !!}"><button type="button" class="btn btn-inverse btn-icon btn-circle m-b-10"><i class="fa fa-plus"></i></button></a>
            @endif
            @if($maritalstatusesdata['usersaccountsroles'][0]->_report==1)
            <a href="{!! url('admin/maritalstatusesreport') !!}"><button type="button" class="btn btn-inverse btn-icon btn-circle m-b-10"><i class="fa fa-file-text-o"></i></button></a>
            @endif
            @if($maritalstatusesdata['usersaccountsroles'][0]->_report==1 || $maritalstatusesdata['usersaccountsroles'][0]->_list==1)
            <a href="#modal-dialog"  data-toggle="modal"><button type="button" class="btn btn-inverse btn-icon btn-circle m-b-10"><i class="fa fa-filter"></i></button></a>
            @endif
    @if($maritalstatusesdata['usersaccountsroles'][0]->_list==1)
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-inverse">
                <div class="panel-heading">
                    <div class="panel-heading-btn">
                        <a href="#" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                        <a href="#" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
                        <a href="#" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                        <a href="#" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                    </div>
                    <h4 class="panel-title">DataTable - Autofill</h4>
                </div>
                <div class="panel-body">
                    <table id="data-table" class="table table-striped table-bordered">
                        <thead>
                                    <tr>
                                        <th>Code</th>
                                        <th>Name</th>
                                        <th>Action</th>                                    </tr>
                        </thead>
                        <tbody>
                        @foreach ($maritalstatusesdata['list'] as $maritalstatuses)
                            <tr>
                                <td class='table-text'><div>
                                	{!! $maritalstatuses->code !!}
                                </div></td>
                                <td class='table-text'><div>
                                	{!! $maritalstatuses->name !!}
                                </div></td>
                                <td>
                <form action="{!! route('maritalstatuses.destroy',$maritalstatuses->id) !!}" method="POST">
                                        @if($maritalstatusesdata['usersaccountsroles'][0]->_show==1)
                                        <a href="{!! route('maritalstatuses.show',$maritalstatuses->id) !!}" id='show-maritalstatuses-{!! $maritalstatuses->id !!}' class='btn btn-sm btn-circle btn-inverse'>
                                            <i class='fa fa-btn fa-eye'></i>
                                        </a>
                                        @endif
                                        @if($maritalstatusesdata['usersaccountsroles'][0]->_edit==1)
                                        <a href="{!! route('maritalstatuses.edit',$maritalstatuses->id) !!}" id='edit-maritalstatuses-{!! $maritalstatuses->id !!}' class='btn btn-sm btn-circle btn-warning'>
                                            <i class='fa fa-btn fa-edit'></i>
                                        </a>
                                        @endif
                                        @if($maritalstatusesdata['usersaccountsroles'][0]->_delete==1)
                                        <input type="hidden" name="_method" value="delete" />
                                        {!! csrf_field() !!}
                                        {!! method_field('DELETE') !!}
                                        <button type='submit' id='delete-maritalstatuses-{!! $maritalstatuses->id !!}' class='btn btn-sm btn-circle btn-danger'>
                                            <i class='fa fa-btn fa-trash'></i>
                                        </button>
                                        @endif
                </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
    @endif
<div class="modal fade modal-message" id="modal-dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">close</button>
                <h4 class="modal-title">Marital Statuses - Filter Dialog</h4>
            </div>
            <div class="modal-body">
    			<div class="row">
                    <div class="col-md-12">
                        <div class="panel panel-inverse">
                            <div class="panel-heading">
                                <div class="panel-heading-btn">
                                    <a href="#" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                                    <a href="#" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
                                    <a href="#" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                                    <a href="#" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                                </div>
                                <h4 class="panel-title">DataForm - Autofill</h4>
                            </div>
                            <div class="panel-body">
                    <form id="form"  class="form-horizontal" action="{!! url('admin/maritalstatusesfilter') !!}" method="POST">
                        {!! csrf_field() !!}
                                <div class="form-group">
                                    <label for="Code" class="col-sm-3 control-label">Code</label>
                                    <div class="col-sm-6">
                                        <input type="text" name="code"  id="code" class="form-control" placeholder="Code" value="">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="Name" class="col-sm-3 control-label">Name</label>
                                    <div class="col-sm-6">
                                        <input type="text" name="name"  id="name" class="form-control" placeholder="Name" value="">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-sm-offset-3 col-sm-6">
                                    <div class="col-sm-offset-3 col-sm-6">
                                        <button type="submit" class="btn btn-sm btn-inverse">
                                            <i class="fa fa-btn fa-search"></i> Search Marital Statuses
                                        </button>
                                    </div>
                                </div>
                    </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <a href="javascript:;" class="btn btn-sm btn-white" data-dismiss="modal">Close</a>
            </div>
        </div>
    </div>
</div>
@endsection
@section('script')
@endsection