routes/web.php
Route::get('/admin/productstocksreport', 'admin\ProductStocksController@report');

Route::post('/admin/productstocksfilter', 'admin\ProductStocksController@filter');

//ProductTransfers routes .....

Route::resource('admin/producttransfers','admin\ProductTransfersController');

Route::get('/admin/producttransfersreport', 'admin\ProductTransfersController@report');

Route::post('/admin/producttransfersfilter', 'admin\ProductTransfersController@filter');

//PurchaseOrderApprovalMappings routes .....

Route::resource('admin/purchaseorderapprovalmappings','admin\PurchaseOrderApprovalMappingsController');

Route::get('/admin/purchaseorderapprovalmappingsreport', 'admin\PurchaseOrderApprovalMappingsController@report');

Route::post('/admin/purchaseorderapprovalmappingsfilter', 'admin\PurchaseOrderApprovalMappingsController@filter');

//PurchaseOrderApprovalMappings routes .....

Route::resource('admin/purchaseorderapprovalmappings','admin\PurchaseOrderApprovalMappingsController');

Route::get('/admin/purchaseorderapprovalmappingsreport', 'admin\PurchaseOrderApprovalMappingsController@report');

Route::post('/admin/purchaseorderapprovalmappingsfilter', 'admin\PurchaseOrderApprovalMappingsController@filter');

//PurchaseOrderApprovalMappings routes .....

Route::resource('admin/purchaseorderapprovalmappings','admin\PurchaseOrderApprovalMappingsController');

Route::get('/admin/purchaseorderapprovalmappingsreport', 'admin\PurchaseOrderApprovalMappingsController@report');

Route::post('/admin/purchaseorderapprovalmappingsfilter', 'admin\PurchaseOrderApprovalMappingsController@filter');

//PurchaseOrderAccountMappings routes .....

Route::resource('admin/purchaseorderaccountmappings','admin\PurchaseOrderAccountMappingsController');

Route::get('/admin/purchaseorderaccountmappingsreport', 'admin\PurchaseOrderAccountMappingsController@report');

Route::post('/admin/purchaseorderaccountmappingsfilter', 'admin\PurchaseOrderAccountMappingsController@filter');

//PurchaseOrderAccountMappings routes .....

Route::resource('admin/purchaseorderaccountmappings','admin\PurchaseOrderAccountMappingsController');

Route::get('/admin/purchaseorderaccountmappingsreport', 'admin\PurchaseOrderAccountMappingsController@report');

Route::post('/admin/purchaseorderaccountmappingsfilter', 'admin\PurchaseOrderAccountMappingsController@filter');

//Loan Statement

Route::resource('admin/loanstatement','admin\LoanStatementController');

// Route::resource('admin/cashbook','admin\CashBookController');

Route::resource('admin/paymentmodesreport','admin\PaymentModesReportController');

Route::resource('admin/lgfstatement','admin\LgfStatementController');

//ProductTransferStatuses routes .....

Route::resource('admin/producttransferstatuses','admin\ProductTransferStatusesController');

Route::get('/admin/producttransferstatusesreport', 'admin\ProductTransferStatusesController@report');

Route::post('/admin/producttransferstatusesfilter', 'admin\ProductTransferStatusesController@filter');

//SalesOrderMarginAccountMappings routes .....

Route::resource('admin/salesordermarginaccountmappings','admin\SalesOrderMarginAccountMappingsController');

Route::get('/admin/salesordermarginaccountmappingsreport', 'admin\SalesOrderMarginAccountMappingsController@report');

Route::post('/admin/salesordermarginaccountmappingsfilter', 'admin\SalesOrderMarginAccountMappingsController@filter');

//LoanProductAssets routes .....

Route::resource('admin/loanproductassets','admin\LoanProductAssetsController');

Route::get('/admin/loanproductassetsreport', 'admin\LoanProductAssetsController@report');

Route::post('/admin/loanproductassetsfilter', 'admin\LoanProductAssetsController@filter');

//LoanProductAssets routes .....

Route::resource('admin/loanproductassets','admin\LoanProductAssetsController');

Route::get('/admin/loanproductassetsreport', 'admin\LoanProductAssetsController@report');

Route::post('/admin/loanproductassetsfilter', 'admin\LoanProductAssetsController@filter');

//LgfTransferTypes routes .....

Route::resource('admin/lgftransfertypes','admin\LgfTransferTypesController');

Route::get('/admin/lgftransfertypesreport', 'admin\LgfTransferTypesController@report');

Route::post('/admin/lgftransfertypesfilter', 'admin\LgfTransferTypesController@filter');

//LgfTransferTypes routes .....

Route::resource('admin/lgftransfertypes','admin\LgfTransferTypesController');

Route::get('/admin/lgftransfertypesreport', 'admin\LgfTransferTypesController@report');

Route::post('/admin/lgftransfertypesfilter', 'admin\LgfTransferTypesController@filter');

//LgfTransferTypes routes .....

Route::resource('admin/lgftransfertypes','admin\LgfTransferTypesController');

Route::get('/admin/lgftransfertypesreport', 'admin\LgfTransferTypesController@report');

Route::post('/admin/lgftransfertypesfilter', 'admin\LgfTransferTypesController@filter');

//LgfTransferTypes routes .....

Route::resource('admin/lgftransfertypes','admin\LgfTransferTypesController');

Route::get('/admin/lgftransfertypesreport', 'admin\LgfTransferTypesController@report');

Route::post('/admin/lgftransfertypesfilter', 'admin\LgfTransferTypesController@filter');

//LgfTransferTypes routes .....

Route::resource('admin/lgftransfertypes','admin\LgfTransferTypesController');

Route::get('/admin/lgftransfertypesreport', 'admin\LgfTransferTypesController@report');

Route::post('/admin/lgftransfertypesfilter', 'admin\LgfTransferTypesController@filter');

//OtherPaymentTypeAccountMappings routes .....

Route::resource('admin/otherpaymenttypeaccountmappings','admin\OtherPaymentTypeAccountMappingsController');

Route::get('/admin/otherpaymenttypeaccountmappingsreport', 'admin\OtherPaymentTypeAccountMappingsController@report');

Route::post('/admin/otherpaymenttypeaccountmappingsfilter', 'admin\OtherPaymentTypeAccountMappingsController@filter');

//OtherPaymentTypeAccountMappings routes .....

Route::resource('admin/otherpaymenttypeaccountmappings','admin\OtherPaymentTypeAccountMappingsController');

Route::get('/admin/otherpaymenttypeaccountmappingsreport', 'admin\OtherPaymentTypeAccountMappingsController@report');

Route::post('/admin/otherpaymenttypeaccountmappingsfilter', 'admin\OtherPaymentTypeAccountMappingsController@filter');

//OtherPaymentTypeAccountMappings routes .....

Route::resource('admin/otherpaymenttypeaccountmappings','admin\OtherPaymentTypeAccountMappingsController');

Route::get('/admin/otherpaymenttypeaccountmappingsreport', 'admin\OtherPaymentTypeAccountMappingsController@report');

Route::post('/admin/otherpaymenttypeaccountmappingsfilter', 'admin\OtherPaymentTypeAccountMappingsController@filter');

//LgfTransferApprovalLevels routes .....

Route::resource('admin/lgftransferapprovallevels','admin\LgfTransferApprovalLevelsController');

Route::get('/admin/lgftransferapprovallevelsreport', 'admin\LgfTransferApprovalLevelsController@report');

Route::post('/admin/lgftransferapprovallevelsfilter', 'admin\LgfTransferApprovalLevelsController@filter');

//LgfToLgfTransfers routes .....

Route::resource('admin/lgftolgftransfers','admin\LgfToLgfTransfersController');

Route::get('/admin/lgftolgftransfersreport', 'admin\LgfToLgfTransfersController@report');

Route::post('/admin/lgftolgftransfersfilter', 'admin\LgfToLgfTransfersController@filter');

Route::get('/admin/getlgftolgftransactionnumber', 'admin\LgfToLgfTransfersController@getlgftolgftransactionnumber');

//LgfTransferApprovals routes .....

Route::resource('admin/lgftransferapprovals','admin\LgfTransferApprovalsController');

Route::get('/admin/lgftransferapprovalsreport', 'admin\LgfTransferApprovalsController@report');

Route::post('/admin/lgftransferapprovalsfilter', 'admin\LgfTransferApprovalsController@filter');

//LgfToLoanTransfers routes .....

Route::resource('admin/lgftoloantransfers','admin\LgfToLoanTransfersController');

Route::get('/admin/lgftoloantransfersreport', 'admin\LgfToLoanTransfersController@report');

Route::post('/admin/lgftoloantransfersfilter', 'admin\LgfToLoanTransfersController@filter');

Route::get('/admin/getlgftoloantransactionnumber', 'admin\LgfToLoanTransfersController@getlgftoloantransactionnumber');

//LgfToFineTransfers routes .....

Route::resource('admin/lgftofinetransfers','admin\LgfToFineTransfersController');

Route::get('/admin/lgftofinetransfersreport', 'admin\LgfToFineTransfersController@report');

Route::post('/admin/lgftofinetransfersfilter', 'admin\LgfToFineTransfersController@filter');

Route::get('/admin/getlgftofinetransactionnumber', 'admin\LgfToFineTransfersController@getlgftofinetransactionnumber');

//MobileMoneyGateways routes .....

Route::resource('admin/mobilemoneygateways','admin\MobileMoneyGatewaysController');

Route::get('/admin/mobilemoneygatewaysreport', 'admin\MobileMoneyGatewaysController@report');

Route::post('/admin/mobilemoneygatewaysfilter', 'admin\MobileMoneyGatewaysController@filter');

//LgfToMobileMoneyTransfers routes .....

Route::resource('admin/lgftomobilemoneytransfers','admin\LgfToMobileMoneyTransfersController');

Route::get('/admin/lgftomobilemoneytransfersreport', 'admin\LgfToMobileMoneyTransfersController@report');

Route::post('/admin/lgftomobilemoneytransfersfilter', 'admin\LgfToMobileMoneyTransfersController@filter');

Route::get('/admin/getlgftomobiletransactionnumber', 'admin\LgfToMobileMoneyTransfersController@getlgftomobiletransactionnumber');

//TransactionGateways routes .....

Route::resource('admin/transactiongateways','admin\TransactionGatewaysController');

Route::get('/admin/transactiongatewaysreport', 'admin\TransactionGatewaysController@report');

Route::post('/admin/transactiongatewaysfilter', 'admin\TransactionGatewaysController@filter');

//WithdrawalModes routes .....

Route::resource('admin/withdrawalmodes','admin\WithdrawalModesController');

Route::get('/admin/withdrawalmodesreport', 'admin\WithdrawalModesController@report');

Route::post('/admin/withdrawalmodesfilter', 'admin\WithdrawalModesController@filter');

app/LoanProductAssets.php
<?php
/**
* @author  Wanjala Innocent Khaemba
*Model - ()
*/
namespace App;
use Illuminate\Database\Eloquent\Model;
class LoanProductAssets extends Model
{
	public function loanproductmodel(){
		return $this->belongsTo(LoanProducts::class, 'loan_product');
	}
	public function assetmodel(){
		return $this->belongsTo(Products::class, 'asset');
	}
}

resources/views/admin/loan_product_assets/chart.blade.php
@extends("admin.home")
@section("main_content")
		<div id="content" class="content">
			<ol class="breadcrumb pull-right">
				<li><a href="#">Home</a></li>
				<li><a href="#">Loan Product Assets</a></li>
				<li class="active">Chart</li>
			</ol>
			<h1 class="page-header">Loan Product Assets Chart <small>loan product assets chart goes here...</small></h1>
            <div class="row">
                <div class="col-md-12">
                    <a href="{!! route('loanproductassets.index') !!}"><button type="button" class="btn btn-inverse btn-icon btn-circle m-b-10"><i class="fa fa-arrow-left"></i></button></a>
                </div>
            </div>
			<div class="row">
			    <div class="col-md-6">
                    <div class="panel panel-inverse" data-sortable-id="chart-js-1">
                        <div class="panel-heading">
                            <div class="panel-heading-btn">
                                <a href="#" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                                <a href="#" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
                                <a href="#" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                                <a href="#" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                            </div>
                            <h4 class="panel-title">Line Chart</h4>
                        </div>
                        <div class="panel-body">
                            <p>
                                A line chart is a way of plotting data points on a line.Often, it is used to show trend data, and the comparison of two data sets.
                            </p>
                            <div>
                                <canvas id="line-chart" data-render="chart-js"></canvas>
                            </div>
                        </div>
                    </div>
		        </div>
		    </div>
		</div>
@endsection

resources/views/admin/loan_product_assets/create.blade.php
@extends("admin.home")
@section("main_content")
<div id="content" class="content">
    <ol class="breadcrumb pull-right">
        <li><a href="#">Home</a></li>
        <li><a href="#">public</a></li>
        <li><a href="#">Loan Product Assets</a></li>
        <li class="active">form</li>
    </ol>
    <h1 class="page-header">Loan Product Assets Form <small>loan product assets details goes here...</small></h1>
    <div class="row">
        <div class="col-md-12">
            <a href="{!! route('loanproductassets.index') !!}"><button type="button" class="btn btn-inverse btn-icon btn-circle m-b-10"><i class="fa fa-arrow-left"></i></button></a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-inverse">
                <div class="panel-heading">
                    <div class="panel-heading-btn">
                        <a href="#" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                        <a href="#" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
                        <a href="#" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                        <a href="#" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                    </div>
                    <h4 class="panel-title">DataForm - Autofill</h4>
                </div>
                <div class="panel-body">
                    <form id="form"  class="form-horizontal" enctype="multipart/form-data">
                        {!! csrf_field() !!}
                                <div class="form-group">
                                    <label for="Loan Product" class="col-sm-3 control-label">Loan Product</label>
                                    <div class="col-sm-6">
									    <select class="form-control selectpicker" data-size="100000" data-live-search="true" data-style="btn-white" name="loan_product"  id="loan_product">
                                            <option value="" >Select Loan Product</option>				                                @foreach ($loanproductassetsdata['loanproducts'] as $loanproducts)
				                                <option value="{!! $loanproducts->id !!}">
					
				                                {!! $loanproducts->name!!}
				                                </option>
				                                @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="Asset" class="col-sm-3 control-label">Asset</label>
                                    <div class="col-sm-6">
									    <select class="form-control selectpicker" data-size="100000" data-live-search="true" data-style="btn-white" name="asset"  id="asset">
                                            <option value="" >Select Asset</option>				                                @foreach ($loanproductassetsdata['products'] as $products)
				                                <option value="{!! $products->id !!}">
					
				                                {!! $products->product_number!!}
				                                {!! $products->name!!}
				                                </option>
				                                @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="Quantity" class="col-sm-3 control-label">Quantity</label>
                                    <div class="col-sm-6">
                                        <input type="text" name="quantity"  id="quantity" class="form-control" placeholder="Quantity" value="">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-sm-offset-3 col-sm-6">
                                        <button type="button" onclick="save()" class="btn btn-sm btn-primary" id="btn-save">
                                            <i class="fa fa-btn fa-plus"></i> Add Loan Product Assets
                                        </button>
                                    </div>
                                </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script language="javascript" type="text/javascript">
function save(){
	$("#btn-save").attr("disable",true);
	var formData = new FormData($('#form')[0]);
	$.ajax({
		type:'POST',
		url: "{!! route('loanproductassets.store')!!}",
		data:formData,
		cache:false,
		contentType: false,
		processData: false,
		success:function(data){
		$("#btn-save").attr("disable",false);
			var obj = jQuery.parseJSON( data );
			if(obj.status=='1'){
				$.gritter.add({
					title: 'Success',
					text: obj.message,
					sticky: false,
					time: '1000',
				});
				$("#form")[0].reset();
			}else{
				$.gritter.add({
					title: 'Fail',
					text: obj.message,
					sticky: false,
					time: '5000',
				});
			}
		},error: function(data){
console.log(data)
			$.gritter.add({
				title: 'Error',
				text: 'An Error occured. Please review your data then submit again!!',
				sticky: false,
				time: '5000',
			});
		}
	});
	return false;
}
</script>
@endsection
@section('script')
<script language="javascript" type="text/javascript">
</script>
@endsection

resources/views/admin/loan_product_assets/index.blade.php
@extends("admin.home")
@section("main_content")
<style type="text/css">
	td div img{
		max-width: 64px;
	}
</style>
<div id="content" class="content">
    <ol class="breadcrumb pull-right">
        <li><a href="#">Home</a></li>
        <li><a href="#">Public</a></li>
        <li><a href="#">Loan Product Assets</a></li>
        <li class="active">Table</li>
    </ol>
    <h1 class="page-header">Loan Product Assets - DATA <small>loan product assets data goes here...</small></h1>
    <div class="row">
        <div class="col-md-12">
            @if($loanproductassetsdata['usersaccountsroles'][0]->_add==1)
            <a href="{!! route('loanproductassets.create') !!}"><button type="button" class="btn btn-inverse btn-icon btn-circle m-b-10"><i class="fa fa-plus"></i></button></a>
            @endif
            @if($loanproductassetsdata['usersaccountsroles'][0]->_report==1)
            <a href="{!! url('admin/loanproductassetsreport') !!}"><button type="button" class="btn btn-inverse btn-icon btn-circle m-b-10"><i class="fa fa-file-text-o"></i></button></a>
            @endif
            @if($loanproductassetsdata['usersaccountsroles'][0]->_report==1 || $loanproductassetsdata['usersaccountsroles'][0]->_list==1)
            <a href="#modal-dialog"  data-toggle="modal"><button type="button" class="btn btn-inverse btn-icon btn-circle m-b-10"><i class="fa fa-filter"></i></button></a>
            @endif
        </div>
    </div>
    @if($loanproductassetsdata['usersaccountsroles'][0]->_list==1)
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-inverse">
                <div class="panel-heading">
                    <div class="panel-heading-btn">
                        <a href="#" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                        <a href="#" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
                        <a href="#" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                        <a href="#" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                    </div>
                    <h4 class="panel-title">DataTable - Autofill</h4>
                </div>
                <div class="panel-body">
                    <table id="data-table" class="table table-striped table-bordered">
                        <thead>
                                    <tr>
                                        <th>Loan Product</th>
                                        <th>Asset</th>
                                        <th>Quantity</th>
                                        <th>Action</th>                                    </tr>
                        </thead>
                        <tbody>
                        @foreach ($loanproductassetsdata['list'] as $loanproductassets)
                            <tr>
                                <td class='table-text'><div>
                                	{!! $loanproductassets->loanproductmodel->name !!}
                                </div></td>
                                <td class='table-text'><div>
                                	{!! $loanproductassets->assetmodel->product_number !!}
                                	{!! $loanproductassets->assetmodel->name !!}
                                </div></td>
                                <td class='table-text'><div>
                                	{!! $loanproductassets->quantity !!}
                                </div></td>
                                <td>
                <form action="{!! route('loanproductassets.destroy',$loanproductassets->id) !!}" method="POST">
                                        @if($loanproductassetsdata['usersaccountsroles'][0]->_show==1)
                                        <a href="{!! route('loanproductassets.show',$loanproductassets->id) !!}" id='show-loanproductassets-{!! $loanproductassets->id !!}' class='btn btn-sm btn-circle btn-inverse'>
                                            <i class='fa fa-btn fa-eye'></i>
                                        </a>
                                        @endif
                                        @if($loanproductassetsdata['usersaccountsroles'][0]->_edit==1)
                                        <a href="{!! route('loanproductassets.edit',$loanproductassets->id) !!}" id='edit-loanproductassets-{!! $loanproductassets->id !!}' class='btn btn-sm btn-circle btn-warning'>
                                            <i class='fa fa-btn fa-edit'></i>
                                        </a>
                                        @endif
                                        @if($loanproductassetsdata['usersaccountsroles'][0]->_delete==1)
                                        <input type="hidden" name="_method" value="delete" />
                                        {!! csrf_field() !!}
                                        {!! method_field('DELETE') !!}
                                        <button type='submit' id='delete-loanproductassets-{!! $loanproductassets->id !!}' class='btn btn-sm btn-circle btn-danger'>
                                            <i class='fa fa-btn fa-trash'></i>
                                        </button>
                                        @endif
                </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
    @endif
<div class="modal fade modal-message" id="modal-dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">close</button>
                <h4 class="modal-title">Loan Product Assets - Filter Dialog</h4>
            </div>
            <div class="modal-body">
    			<div class="row">
                    <div class="col-md-12">
                        <div class="panel panel-inverse">
                            <div class="panel-heading">
                                <div class="panel-heading-btn">
                                    <a href="#" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                                    <a href="#" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
                                    <a href="#" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                                    <a href="#" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                                </div>
                                <h4 class="panel-title">DataForm - Autofill</h4>
                            </div>
                            <div class="panel-body">
                    <form id="form"  class="form-horizontal" action="{!! url('admin/loanproductassetsfilter') !!}" method="POST">
                        {!! csrf_field() !!}
                                <div class="form-group">
                                    <label for="Loan Product" class="col-sm-3 control-label">Loan Product</label>
                                    <div class="col-sm-6">
									    <select class="form-control selectpicker" data-size="100000" data-live-search="true" data-style="btn-white" name="loan_product"  id="loan_product">
                                            <option value="" >Select Loan Product</option>				                                @foreach ($loanproductassetsdata['loanproducts'] as $loanproducts)
				                                <option value="{!! $loanproducts->id !!}">
					
				                                {!! $loanproducts->name!!}
				                                </option>
				                                @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="Asset" class="col-sm-3 control-label">Asset</label>
                                    <div class="col-sm-6">
									    <select class="form-control selectpicker" data-size="100000" data-live-search="true" data-style="btn-white" name="asset"  id="asset">
                                            <option value="" >Select Asset</option>				                                @foreach ($loanproductassetsdata['products'] as $products)
				                                <option value="{!! $products->id !!}">
					
				                                {!! $products->product_number!!}
				                                {!! $products->name!!}
				                                </option>
				                                @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="Quantity" class="col-sm-3 control-label">Quantity</label>
                                    <div class="col-sm-6">
                                        <input type="text" name="quantity"  id="quantity" class="form-control" placeholder="Quantity" value="">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-sm-offset-3 col-sm-6">
                                    <div class="col-sm-offset-3 col-sm-6">
                                        <button type="submit" class="btn btn-sm btn-inverse">
                                            <i class="fa fa-btn fa-search"></i> Search Loan Product Assets
                                        </button>
                                    </div>
                                </div>
                    </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <a href="javascript:;" class="btn btn-sm btn-white" data-dismiss="modal">Close</a>
            </div>
        </div>
    </div>
</div>
@endsection
@section('script')
@endsection