routes/web.php
Route::get('/admin/finetransferapprovalsreport', 'admin\FineTransferApprovalsController@report');

Route::post('/admin/finetransferapprovalsfilter', 'admin\FineTransferApprovalsController@filter');

//MobileMoneyTransferApprovalLevels routes .....

Route::resource('admin/mobilemoneytransferapprovallevels','admin\MobileMoneyTransferApprovalLevelsController');

Route::get('/admin/mobilemoneytransferapprovallevelsreport', 'admin\MobileMoneyTransferApprovalLevelsController@report');

Route::post('/admin/mobilemoneytransferapprovallevelsfilter', 'admin\MobileMoneyTransferApprovalLevelsController@filter');

//MobileMoneyTransferApprovals routes .....

Route::resource('admin/mobilemoneytransferapprovals','admin\MobileMoneyTransferApprovalsController');

Route::get('/admin/mobilemoneytransferapprovalsreport', 'admin\MobileMoneyTransferApprovalsController@report');

Route::post('/admin/mobilemoneytransferapprovalsfilter', 'admin\MobileMoneyTransferApprovalsController@filter');

//LgfToLoanTransfers routes .....

Route::resource('admin/lgftoloantransfers','admin\LgfToLoanTransfersController');

Route::get('/admin/lgftoloantransfersreport', 'admin\LgfToLoanTransfersController@report');

Route::post('/admin/lgftoloantransfersfilter', 'admin\LgfToLoanTransfersController@filter');

//LgfToFineTransfers routes .....

Route::resource('admin/lgftofinetransfers','admin\LgfToFineTransfersController');

Route::get('/admin/lgftofinetransfersreport', 'admin\LgfToFineTransfersController@report');

Route::post('/admin/lgftofinetransfersfilter', 'admin\LgfToFineTransfersController@filter');

//LoanTransferApprovals routes .....

Route::resource('admin/loantransferapprovals','admin\LoanTransferApprovalsController');

Route::get('/admin/loantransferapprovalsreport', 'admin\LoanTransferApprovalsController@report');

Route::post('/admin/loantransferapprovalsfilter', 'admin\LoanTransferApprovalsController@filter');

//FineTransferApprovalLevels routes .....

Route::resource('admin/finetransferapprovallevels','admin\FineTransferApprovalLevelsController');

Route::get('/admin/finetransferapprovallevelsreport', 'admin\FineTransferApprovalLevelsController@report');

Route::post('/admin/finetransferapprovallevelsfilter', 'admin\FineTransferApprovalLevelsController@filter');

//FineTransferApprovals routes .....

Route::resource('admin/finetransferapprovals','admin\FineTransferApprovalsController');

Route::get('/admin/finetransferapprovalsreport', 'admin\FineTransferApprovalsController@report');

Route::post('/admin/finetransferapprovalsfilter', 'admin\FineTransferApprovalsController@filter');

//AccountTransferApprovals routes .....

Route::resource('admin/accounttransferapprovals','admin\AccountTransferApprovalsController');

Route::get('/admin/accounttransferapprovalsreport', 'admin\AccountTransferApprovalsController@report');

Route::post('/admin/accounttransferapprovalsfilter', 'admin\AccountTransferApprovalsController@filter');

//WithdrawalChargeConfigurations routes .....

Route::resource('admin/withdrawalchargeconfigurations','admin\WithdrawalChargeConfigurationsController');

Route::get('/admin/withdrawalchargeconfigurationsreport', 'admin\WithdrawalChargeConfigurationsController@report');

Route::post('/admin/withdrawalchargeconfigurationsfilter', 'admin\WithdrawalChargeConfigurationsController@filter');

//MobileMoneyModes routes .....

Route::resource('admin/mobilemoneymodes','admin\MobileMoneyModesController');

Route::get('/admin/mobilemoneymodesreport', 'admin\MobileMoneyModesController@report');

Route::post('/admin/mobilemoneymodesfilter', 'admin\MobileMoneyModesController@filter');

//MobileMoneyChargeConfigurations routes .....

Route::resource('admin/mobilemoneychargeconfigurations','admin\MobileMoneyChargeConfigurationsController');

Route::get('/admin/mobilemoneychargeconfigurationsreport', 'admin\MobileMoneyChargeConfigurationsController@report');

Route::post('/admin/mobilemoneychargeconfigurationsfilter', 'admin\MobileMoneyChargeConfigurationsController@filter');

Route::get('/admin/getmobilemoneytransactioncharge/{clientid}/{mobilemoneymodeid}/{amount}', 'admin\MobileMoneyChargeConfigurationsController@gettransactioncharge');

//LgfToMobileMoneyApprovalLevels routes .....

Route::resource('admin/lgftomobilemoneyapprovallevels','admin\LgfToMobileMoneyApprovalLevelsController');

Route::get('/admin/lgftomobilemoneyapprovallevelsreport', 'admin\LgfToMobileMoneyApprovalLevelsController@report');

Route::post('/admin/lgftomobilemoneyapprovallevelsfilter', 'admin\LgfToMobileMoneyApprovalLevelsController@filter');

//LgfToMobileMoneyApprovals routes .....

Route::resource('admin/lgftomobilemoneyapprovals','admin\LgfToMobileMoneyApprovalsController');

Route::get('/admin/lgftomobilemoneyapprovalsreport', 'admin\LgfToMobileMoneyApprovalsController@report');

Route::post('/admin/lgftomobilemoneyapprovalsfilter', 'admin\LgfToMobileMoneyApprovalsController@filter');

//MobileMoneyTransferApprovalLevels routes .....

Route::resource('admin/mobilemoneytransferapprovallevels','admin\MobileMoneyTransferApprovalLevelsController');

Route::get('/admin/mobilemoneytransferapprovallevelsreport', 'admin\MobileMoneyTransferApprovalLevelsController@report');

Route::post('/admin/mobilemoneytransferapprovallevelsfilter', 'admin\MobileMoneyTransferApprovalLevelsController@filter');

//MobileMoneyTransferApprovals routes .....

Route::resource('admin/mobilemoneytransferapprovals','admin\MobileMoneyTransferApprovalsController');

Route::get('/admin/mobilemoneytransferapprovalsreport', 'admin\MobileMoneyTransferApprovalsController@report');

Route::post('/admin/mobilemoneytransferapprovalsfilter', 'admin\MobileMoneyTransferApprovalsController@filter');

//MobileMoneyChargeScales routes .....

Route::resource('admin/mobilemoneychargescales','admin\MobileMoneyChargeScalesController');

Route::get('/admin/mobilemoneychargescalesreport', 'admin\MobileMoneyChargeScalesController@report');

Route::post('/admin/mobilemoneychargescalesfilter', 'admin\MobileMoneyChargeScalesController@filter');

//MobileMoneyTransferConfigurations routes .....

Route::resource('admin/mobilemoneytransferconfigurations','admin\MobileMoneyTransferConfigurationsController');

Route::get('/admin/mobilemoneytransferconfigurationsreport', 'admin\MobileMoneyTransferConfigurationsController@report');

Route::post('/admin/mobilemoneytransferconfigurationsfilter', 'admin\MobileMoneyTransferConfigurationsController@filter');

//MobileMoneyTransactionChargeConfigurations routes .....

Route::resource('admin/mmtransactionchargeconfigurations','admin\MobileMoneyTransactionChargeConfigurationsController');

Route::get('/admin/mobilemoneytransactionchargeconfigurationsreport', 'admin\MobileMoneyTransactionChargeConfigurationsController@report');

Route::post('/admin/mobilemoneytransactionchargeconfigurationsfilter', 'admin\MobileMoneyTransactionChargeConfigurationsController@filter');

//LgfToBankTransfers routes .....

Route::resource('admin/lgftobanktransfers','admin\LgfToBankTransfersController');

Route::get('/admin/lgftobanktransfersreport', 'admin\LgfToBankTransfersController@report');

Route::post('/admin/lgftobanktransfersfilter', 'admin\LgfToBankTransfersController@filter');

Route::get('/admin/getlgftobanktransactionnumber', 'admin\LgfToBankTransfersController@getlgftobanktransactionnumber');

//LgfToInventoryTransfers routes .....

Route::resource('admin/lgftoinventorytransfers','admin\LgfToInventoryTransfersController');

Route::get('/admin/lgftoinventorytransfersreport', 'admin\LgfToInventoryTransfersController@report');

Route::post('/admin/lgftoinventorytransfersfilter', 'admin\LgfToInventoryTransfersController@filter');

Route::get('/admin/getgftoinventorytransactionnumber', 'admin\LgfToInventoryTransfersController@getgftoinventorytransactionnumber');

//InventoryTransferApprovalLevels routes .....

Route::resource('admin/inventorytransferapprovallevels','admin\InventoryTransferApprovalLevelsController');

Route::get('/admin/inventorytransferapprovallevelsreport', 'admin\InventoryTransferApprovalLevelsController@report');

Route::post('/admin/inventorytransferapprovallevelsfilter', 'admin\InventoryTransferApprovalLevelsController@filter');

//BankTransferApprovalLevels routes .....

Route::resource('admin/banktransferapprovallevels','admin\BankTransferApprovalLevelsController');

Route::get('/admin/banktransferapprovallevelsreport', 'admin\BankTransferApprovalLevelsController@report');

Route::post('/admin/banktransferapprovallevelsfilter', 'admin\BankTransferApprovalLevelsController@filter');

//InventoryTransferApprovals routes .....

Route::resource('admin/inventorytransferapprovals','admin\InventoryTransferApprovalsController');

Route::get('/admin/inventorytransferapprovalsreport', 'admin\InventoryTransferApprovalsController@report');

Route::post('/admin/inventorytransferapprovalsfilter', 'admin\InventoryTransferApprovalsController@filter');

//BankTransferApprovals routes .....

Route::resource('admin/banktransferapprovals','admin\BankTransferApprovalsController');

Route::get('/admin/banktransferapprovalsreport', 'admin\BankTransferApprovalsController@report');

Route::post('/admin/banktransferapprovalsfilter', 'admin\BankTransferApprovalsController@filter');

//BankTransferCharges routes .....

Route::resource('admin/banktransfercharges','admin\BankTransferChargesController');

Route::get('/admin/banktransferchargesreport', 'admin\BankTransferChargesController@report');

Route::post('/admin/banktransferchargesfilter', 'admin\BankTransferChargesController@filter');

Route::get('/admin/getbanktransactioncharges/{clientid}/{amount}', 'admin\BankTransferChargesController@getbanktransactioncharges');



//BankTransferCharges routes .....

Route::resource('admin/banktransfercharges','admin\BankTransferChargesController');

Route::get('/admin/banktransferchargesreport', 'admin\BankTransferChargesController@report');

app/MobileMoneyModes.php
<?php
/**
* @author  Wanjala Innocent Khaemba
*Model - (mobile money modes)
*/
namespace App;
use Illuminate\Database\Eloquent\Model;
class MobileMoneyModes extends Model
{
}

resources/views/admin/mobile_money_modes/chart.blade.php
@extends("admin.home")
@section("main_content")
		<div id="content" class="content">
			<ol class="breadcrumb pull-right">
				<li><a href="#">Home</a></li>
				<li><a href="#">Mobile Money Modes</a></li>
				<li class="active">Chart</li>
			</ol>
			<h1 class="page-header">Mobile Money Modes Chart <small>mobile money modes chart goes here...</small></h1>
            <div class="row">
                <div class="col-md-12">
                    <a href="{!! route('mobilemoneymodes.index') !!}"><button type="button" class="btn btn-inverse btn-icon btn-circle m-b-10"><i class="fa fa-arrow-left"></i></button></a>
                </div>
            </div>
			<div class="row">
			    <div class="col-md-6">
                    <div class="panel panel-inverse" data-sortable-id="chart-js-1">
                        <div class="panel-heading">
                            <div class="panel-heading-btn">
                                <a href="#" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                                <a href="#" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
                                <a href="#" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                                <a href="#" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                            </div>
                            <h4 class="panel-title">Line Chart</h4>
                        </div>
                        <div class="panel-body">
                            <p>
                                A line chart is a way of plotting data points on a line.Often, it is used to show trend data, and the comparison of two data sets.
                            </p>
                            <div>
                                <canvas id="line-chart" data-render="chart-js"></canvas>
                            </div>
                        </div>
                    </div>
		        </div>
		    </div>
		</div>
@endsection

resources/views/admin/mobile_money_modes/create.blade.php
@extends("admin.home")
@section("main_content")
<div id="content" class="content">
    <ol class="breadcrumb pull-right">
        <li><a href="#">Home</a></li>
        <li><a href="#">public</a></li>
        <li><a href="#">Mobile Money Modes</a></li>
        <li class="active">form</li>
    </ol>
    <h1 class="page-header">Mobile Money Modes Form <small>mobile money modes details goes here...</small></h1>
    <div class="row">
        <div class="col-md-12">
            <a href="{!! route('mobilemoneymodes.index') !!}"><button type="button" class="btn btn-inverse btn-icon btn-circle m-b-10"><i class="fa fa-arrow-left"></i></button></a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-inverse">
                <div class="panel-heading">
                    <div class="panel-heading-btn">
                        <a href="#" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                        <a href="#" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
                        <a href="#" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                        <a href="#" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                    </div>
                    <h4 class="panel-title">DataForm - Autofill</h4>
                </div>
                <div class="panel-body">
                    <form id="form"  class="form-horizontal" enctype="multipart/form-data">
                        {!! csrf_field() !!}
                                <div class="form-group">
                                    <label for="Code" class="col-sm-3 control-label">Code</label>
                                    <div class="col-sm-6">
                                        <input type="text" name="code"  id="code" class="form-control" placeholder="Code" value="">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="Name" class="col-sm-3 control-label">Name</label>
                                    <div class="col-sm-6">
                                        <input type="text" name="name"  id="name" class="form-control" placeholder="Name" value="">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="Description" class="col-sm-3 control-label">Description</label>
                                    <div class="col-sm-6">
                                        <Textarea name="description" id="description"  class="form-control" row="20" placeholder="Description" value=""></textarea>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-sm-offset-3 col-sm-6">
                                        <button type="button" onclick="save()" class="btn btn-sm btn-primary" id="btn-save">
                                            <i class="fa fa-btn fa-plus"></i> Add Mobile Money Modes
                                        </button>
                                    </div>
                                </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script language="javascript" type="text/javascript">
function save(){
	$("#btn-save").attr("disable",true);
	var formData = new FormData($('#form')[0]);
	$.ajax({
		type:'POST',
		url: "{!! route('mobilemoneymodes.store')!!}",
		data:formData,
		cache:false,
		contentType: false,
		processData: false,
		success:function(data){
		$("#btn-save").attr("disable",false);
			var obj = jQuery.parseJSON( data );
			if(obj.status=='1'){
				$.gritter.add({
					title: 'Success',
					text: obj.message,
					sticky: false,
					time: '1000',
				});
				$("#form")[0].reset();
			}else{
				$.gritter.add({
					title: 'Fail',
					text: obj.message,
					sticky: false,
					time: '5000',
				});
			}
		},error: function(data){
console.log(data)
			$.gritter.add({
				title: 'Error',
				text: 'An Error occured. Please review your data then submit again!!',
				sticky: false,
				time: '5000',
			});
		}
	});
	return false;
}
</script>
@endsection
@section('script')
<script language="javascript" type="text/javascript">
</script>
@endsection

resources/views/admin/mobile_money_modes/edit.blade.php
@extends("admin.home")
@section("main_content")
<div id="content" class="content">
    <ol class="breadcrumb pull-right">
        <li><a href="#">Home</a></li>
        <li><a href="#">public</a></li>
        <li><a href="#">Mobile Money Modes</a></li>
        <li class="active">form</li>
    </ol>
    <h1 class="page-header">Mobile Money Modes Update Form <small>mobile money modes details goes here...</small></h1>
    <div class="row">
        <div class="col-md-12">
            <a href="{!! route('mobilemoneymodes.index') !!}"><button type="button" class="btn btn-inverse btn-icon btn-circle m-b-10"><i class="fa fa-arrow-left"></i></button></a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-inverse">
                <div class="panel-heading">
                    <div class="panel-heading-btn">
                        <a href="#" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                        <a href="#" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
                        <a href="#" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                        <a href="#" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                    </div>
                    <h4 class="panel-title">DataForm - Autofill</h4>
                </div>
                <div class="panel-body">
                    <form action="{!! route('mobilemoneymodes.update',$mobilemoneymodesdata['data']->id) !!}" method="POST" class="form-horizontal">
<input type="hidden" name="_method" value="put" />
                        {!! csrf_field() !!}
                                <div class="form-group">
                                    <label for="Code" class="col-sm-3 control-label">Code</label>
                                    <div class="col-sm-6">
                                        <input type="text" name="code" id="code" class="form-control" placeholder="Code" value="{!! $mobilemoneymodesdata['data']->code !!}">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="Name" class="col-sm-3 control-label">Name</label>
                                    <div class="col-sm-6">
                                        <input type="text" name="name" id="name" class="form-control" placeholder="Name" value="{!! $mobilemoneymodesdata['data']->name !!}">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="Description" class="col-sm-3 control-label">Description</label>
                                    <div class="col-sm-6">
                                        <Textarea name="description" id="description" class="form-control" row="20" placeholder="Description" value="{!! $mobilemoneymodesdata['data']->description !!}">{!! $mobilemoneymodesdata['data']->description !!}</textarea>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-sm-offset-3 col-sm-6">
                                    <div class="col-sm-offset-3 col-sm-6">
                                        <button type="submit" class="btn btn-sm btn-primary">
                                            <i class="fa fa-btn fa-plus"></i> Edit Mobile Money Modes
                                        </button>
                                    </div>
                                </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('script')
<script language="javascript" type="text/javascript">
</script>
@endsection

resources/views/admin/mobile_money_modes/index.blade.php
@extends("admin.home")
@section("main_content")
<style type="text/css">
	td div img{
		max-width: 64px;
	}
</style>
<div id="content" class="content">
    <ol class="breadcrumb pull-right">
        <li><a href="#">Home</a></li>
        <li><a href="#">Public</a></li>
        <li><a href="#">Mobile Money Modes</a></li>
        <li class="active">Table</li>
    </ol>
    <h1 class="page-header">Mobile Money Modes - DATA <small>mobile money modes data goes here...</small></h1>
    <div class="row">
        <div class="col-md-12">
            @if($mobilemoneymodesdata['usersaccountsroles'][0]->_add==1)
            <a href="{!! route('mobilemoneymodes.create') !!}"><button type="button" class="btn btn-inverse btn-icon btn-circle m-b-10"><i class="fa fa-plus"></i></button></a>
            @endif
            @if($mobilemoneymodesdata['usersaccountsroles'][0]->_report==1)
            <a href="{!! url('admin/mobilemoneymodesreport') !!}"><button type="button" class="btn btn-inverse btn-icon btn-circle m-b-10"><i class="fa fa-file-text-o"></i></button></a>
            @endif
            @if($mobilemoneymodesdata['usersaccountsroles'][0]->_report==1 || $mobilemoneymodesdata['usersaccountsroles'][0]->_list==1)
            <a href="#modal-dialog"  data-toggle="modal"><button type="button" class="btn btn-inverse btn-icon btn-circle m-b-10"><i class="fa fa-filter"></i></button></a>
            @endif
        </div>
    </div>
    @if($mobilemoneymodesdata['usersaccountsroles'][0]->_list==1)
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-inverse">
                <div class="panel-heading">
                    <div class="panel-heading-btn">
                        <a href="#" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                        <a href="#" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
                        <a href="#" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                        <a href="#" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                    </div>
                    <h4 class="panel-title">DataTable - Autofill</h4>
                </div>
                <div class="panel-body">
                    <table id="data-table" class="table table-striped table-bordered">
                        <thead>
                                    <tr>
                                        <th>Code</th>
                                        <th>Name</th>
                                        <th>Description</th>
                                        <th>Action</th>                                    </tr>
                        </thead>
                        <tbody>
                        @foreach ($mobilemoneymodesdata['list'] as $mobilemoneymodes)
                            <tr>
                                <td class='table-text'><div>
                                	{!! $mobilemoneymodes->code !!}
                                </div></td>
                                <td class='table-text'><div>
                                	{!! $mobilemoneymodes->name !!}
                                </div></td>
                                <td class='table-text'><div>
                                	{!! $mobilemoneymodes->description !!}
                                </div></td>
                                <td>
                <form action="{!! route('mobilemoneymodes.destroy',$mobilemoneymodes->id) !!}" method="POST">
                                        @if($mobilemoneymodesdata['usersaccountsroles'][0]->_show==1)
                                        <a href="{!! route('mobilemoneymodes.show',$mobilemoneymodes->id) !!}" id='show-mobilemoneymodes-{!! $mobilemoneymodes->id !!}' class='btn btn-sm btn-circle btn-inverse'>
                                            <i class='fa fa-btn fa-eye'></i>
                                        </a>
                                        @endif
                                        @if($mobilemoneymodesdata['usersaccountsroles'][0]->_edit==1)
                                        <a href="{!! route('mobilemoneymodes.edit',$mobilemoneymodes->id) !!}" id='edit-mobilemoneymodes-{!! $mobilemoneymodes->id !!}' class='btn btn-sm btn-circle btn-warning'>
                                            <i class='fa fa-btn fa-edit'></i>
                                        </a>
                                        @endif
                                        @if($mobilemoneymodesdata['usersaccountsroles'][0]->_delete==1)
                                        <input type="hidden" name="_method" value="delete" />
                                        {!! csrf_field() !!}
                                        {!! method_field('DELETE') !!}
                                        <button type='submit' id='delete-mobilemoneymodes-{!! $mobilemoneymodes->id !!}' class='btn btn-sm btn-circle btn-danger'>
                                            <i class='fa fa-btn fa-trash'></i>
                                        </button>
                                        @endif
                </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
    @endif
<div class="modal fade modal-message" id="modal-dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">close</button>
                <h4 class="modal-title">Mobile Money Modes - Filter Dialog</h4>
            </div>
            <div class="modal-body">
    			<div class="row">
                    <div class="col-md-12">
                        <div class="panel panel-inverse">
                            <div class="panel-heading">
                                <div class="panel-heading-btn">
                                    <a href="#" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                                    <a href="#" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
                                    <a href="#" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                                    <a href="#" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                                </div>
                                <h4 class="panel-title">DataForm - Autofill</h4>
                            </div>
                            <div class="panel-body">
                    <form id="form"  class="form-horizontal" action="{!! url('admin/mobilemoneymodesfilter') !!}" method="POST">
                        {!! csrf_field() !!}
                                <div class="form-group">
                                    <label for="Code" class="col-sm-3 control-label">Code</label>
                                    <div class="col-sm-6">
                                        <input type="text" name="code"  id="code" class="form-control" placeholder="Code" value="">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="Name" class="col-sm-3 control-label">Name</label>
                                    <div class="col-sm-6">
                                        <input type="text" name="name"  id="name" class="form-control" placeholder="Name" value="">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="Description" class="col-sm-3 control-label">Description</label>
                                    <div class="col-sm-6">
                                        <Textarea name="description" id="description"  class="form-control" row="5" placeholder="Description" value=""></textarea>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-sm-offset-3 col-sm-6">
                                    <div class="col-sm-offset-3 col-sm-6">
                                        <button type="submit" class="btn btn-sm btn-inverse">
                                            <i class="fa fa-btn fa-search"></i> Search Mobile Money Modes
                                        </button>
                                    </div>
                                </div>
                    </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <a href="javascript:;" class="btn btn-sm btn-white" data-dismiss="modal">Close</a>
            </div>
        </div>
    </div>
</div>
@endsection
@section('script')
@endsection