routes/web.php
// Route::resource('admin/purchaseorderaccountmapping','admin\PurchaseOrderAccountMappingController');

// Route::get('/admin/purchaseorderaccountmappingreport', 'admin\PurchaseOrderAccountMappingController@report');

// Route::post('/admin/purchaseorderaccountmappingfilter', 'admin\PurchaseOrderAccountMappingController@filter');

//PurchaseOrderAccountMappings routes .....

Route::resource('admin/purchaseorderaccountmappings','admin\PurchaseOrderAccountMappingsController');

Route::get('/admin/purchaseorderaccountmappingsreport', 'admin\PurchaseOrderAccountMappingsController@report');

Route::post('/admin/purchaseorderaccountmappingsfilter', 'admin\PurchaseOrderAccountMappingsController@filter');

//SalesOrders routes .....

Route::resource('admin/salesorders','admin\SalesOrdersController');

Route::get('/admin/salesordersreport', 'admin\SalesOrdersController@report');

Route::post('/admin/salesordersfilter', 'admin\SalesOrdersController@filter');

Route::get('/admin/getsalesorderlines/{id}', 'admin\SalesOrdersController@getsalesorderlines');

Route::get('/admin/getsalesorderpayments/{id}', 'admin\SalesOrdersController@getsalesorderpayments');

Route::get('/admin/createsalesorderpayments/{id}', 'admin\SalesOrdersController@createsalesorderpayments');

Route::post('/admin/storesalesorderpayments/{id}', 'admin\SalesOrdersController@storesalesorderpayments');

Route::get('/admin/getsalesordernumber', 'admin\SalesOrdersController@getsalesordernumber');

//SalesOrderLines routes .....

Route::resource('admin/salesorderlines','admin\SalesOrderLinesController');

Route::get('/admin/salesorderlinesreport', 'admin\SalesOrderLinesController@report');

Route::post('/admin/salesorderlinesfilter', 'admin\SalesOrderLinesController@filter');

//SalesOrderPayments routes .....

Route::resource('admin/salesorderpayments','admin\SalesOrderPaymentsController');

Route::get('/admin/salesorderpaymentsreport', 'admin\SalesOrderPaymentsController@report');

Route::post('/admin/salesorderpaymentsfilter', 'admin\SalesOrderPaymentsController@filter');

//ProductStocks routes .....

Route::resource('admin/productstocks','admin\ProductStocksController');

Route::get('/admin/productstocksreport', 'admin\ProductStocksController@report');

Route::post('/admin/productstocksfilter', 'admin\ProductStocksController@filter');

Route::get('/admin/getstockbystoreid/{id}', 'admin\ProductStocksController@getstockbystoreid');

Route::get('/admin/getstockbyproductidandstoreid/{productid}/{stockid}', 'admin\ProductStocksController@getstockbyproductidandstoreid');

//ProductStocks routes .....

Route::resource('admin/productstocks','admin\ProductStocksController');

Route::get('/admin/productstocksreport', 'admin\ProductStocksController@report');

Route::post('/admin/productstocksfilter', 'admin\ProductStocksController@filter');

//ProductStocks routes .....

Route::resource('admin/productstocks','admin\ProductStocksController');

Route::get('/admin/productstocksreport', 'admin\ProductStocksController@report');

Route::post('/admin/productstocksfilter', 'admin\ProductStocksController@filter');

//ProductStocks routes .....

Route::resource('admin/productstocks','admin\ProductStocksController');

Route::get('/admin/productstocksreport', 'admin\ProductStocksController@report');

Route::post('/admin/productstocksfilter', 'admin\ProductStocksController@filter');

//SalesOrderAccountMappings routes .....

Route::resource('admin/salesorderaccountmappings','admin\SalesOrderAccountMappingsController');

Route::get('/admin/salesorderaccountmappingsreport', 'admin\SalesOrderAccountMappingsController@report');

Route::post('/admin/salesorderaccountmappingsfilter', 'admin\SalesOrderAccountMappingsController@filter');

//Stores routes .....

Route::resource('admin/stores','admin\StoresController');

Route::get('/admin/storesreport', 'admin\StoresController@report');

Route::post('/admin/storesfilter', 'admin\StoresController@filter');

Route::get('/admin/getstorenumber', 'admin\StoresController@getstorenumber');

//ProductStocks routes .....

Route::resource('admin/productstocks','admin\ProductStocksController');

Route::get('/admin/productstocksreport', 'admin\ProductStocksController@report');

Route::post('/admin/productstocksfilter', 'admin\ProductStocksController@filter');

//ProductTransfers routes .....

Route::resource('admin/producttransfers','admin\ProductTransfersController');

Route::get('/admin/producttransfersreport', 'admin\ProductTransfersController@report');

Route::post('/admin/producttransfersfilter', 'admin\ProductTransfersController@filter');

//PurchaseOrderApprovalMappings routes .....

Route::resource('admin/purchaseorderapprovalmappings','admin\PurchaseOrderApprovalMappingsController');

Route::get('/admin/purchaseorderapprovalmappingsreport', 'admin\PurchaseOrderApprovalMappingsController@report');

Route::post('/admin/purchaseorderapprovalmappingsfilter', 'admin\PurchaseOrderApprovalMappingsController@filter');

//PurchaseOrderApprovals routes .....

Route::resource('admin/purchaseorderapprovals','admin\PurchaseOrderApprovalsController');

Route::get('/admin/purchaseorderapprovalsreport', 'admin\PurchaseOrderApprovalsController@report');

Route::post('/admin/purchaseorderapprovalsfilter', 'admin\PurchaseOrderApprovalsController@filter');

//Stores routes .....

Route::resource('admin/stores','admin\StoresController');

Route::get('/admin/storesreport', 'admin\StoresController@report');

Route::post('/admin/storesfilter', 'admin\StoresController@filter');

//Stores routes .....

Route::resource('admin/stores','admin\StoresController');

Route::get('/admin/storesreport', 'admin\StoresController@report');

Route::post('/admin/storesfilter', 'admin\StoresController@filter');

//Stores routes .....

Route::resource('admin/stores','admin\StoresController');

Route::get('/admin/storesreport', 'admin\StoresController@report');

Route::post('/admin/storesfilter', 'admin\StoresController@filter');

//ProductStocks routes .....

Route::resource('admin/productstocks','admin\ProductStocksController');

Route::get('/admin/productstocksreport', 'admin\ProductStocksController@report');

Route::post('/admin/productstocksfilter', 'admin\ProductStocksController@filter');

//ProductStocks routes .....

Route::resource('admin/productstocks','admin\ProductStocksController');

Route::get('/admin/productstocksreport', 'admin\ProductStocksController@report');

Route::post('/admin/productstocksfilter', 'admin\ProductStocksController@filter');

//ProductTransfers routes .....

Route::resource('admin/producttransfers','admin\ProductTransfersController');

Route::get('/admin/producttransfersreport', 'admin\ProductTransfersController@report');

Route::post('/admin/producttransfersfilter', 'admin\ProductTransfersController@filter');

//PurchaseOrderApprovalMappings routes .....

Route::resource('admin/purchaseorderapprovalmappings','admin\PurchaseOrderApprovalMappingsController');

Route::get('/admin/purchaseorderapprovalmappingsreport', 'admin\PurchaseOrderApprovalMappingsController@report');

Route::post('/admin/purchaseorderapprovalmappingsfilter', 'admin\PurchaseOrderApprovalMappingsController@filter');

//PurchaseOrderApprovalMappings routes .....

Route::resource('admin/purchaseorderapprovalmappings','admin\PurchaseOrderApprovalMappingsController');

Route::get('/admin/purchaseorderapprovalmappingsreport', 'admin\PurchaseOrderApprovalMappingsController@report');

Route::post('/admin/purchaseorderapprovalmappingsfilter', 'admin\PurchaseOrderApprovalMappingsController@filter');

//PurchaseOrderApprovalMappings routes .....

Route::resource('admin/purchaseorderapprovalmappings','admin\PurchaseOrderApprovalMappingsController');

Route::get('/admin/purchaseorderapprovalmappingsreport', 'admin\PurchaseOrderApprovalMappingsController@report');

Route::post('/admin/purchaseorderapprovalmappingsfilter', 'admin\PurchaseOrderApprovalMappingsController@filter');

//PurchaseOrderAccountMappings routes .....

Route::resource('admin/purchaseorderaccountmappings','admin\PurchaseOrderAccountMappingsController');

Route::get('/admin/purchaseorderaccountmappingsreport', 'admin\PurchaseOrderAccountMappingsController@report');

Route::post('/admin/purchaseorderaccountmappingsfilter', 'admin\PurchaseOrderAccountMappingsController@filter');

//PurchaseOrderAccountMappings routes .....

Route::resource('admin/purchaseorderaccountmappings','admin\PurchaseOrderAccountMappingsController');

Route::get('/admin/purchaseorderaccountmappingsreport', 'admin\PurchaseOrderAccountMappingsController@report');

Route::post('/admin/purchaseorderaccountmappingsfilter', 'admin\PurchaseOrderAccountMappingsController@filter');

//Loan Statement

Route::resource('admin/loanstatement','admin\LoanStatementController');

// Route::resource('admin/cashbook','admin\CashBookController');

Route::resource('admin/paymentmodesreport','admin\PaymentModesReportController');

Route::resource('admin/lgfstatement','admin\LgfStatementController');

//ProductTransferStatuses routes .....

Route::resource('admin/producttransferstatuses','admin\ProductTransferStatusesController');

Route::get('/admin/producttransferstatusesreport', 'admin\ProductTransferStatusesController@report');

Route::post('/admin/producttransferstatusesfilter', 'admin\ProductTransferStatusesController@filter');

//SalesOrderMarginAccountMappings routes .....

Route::resource('admin/salesordermarginaccountmappings','admin\SalesOrderMarginAccountMappingsController');

Route::get('/admin/salesordermarginaccountmappingsreport', 'admin\SalesOrderMarginAccountMappingsController@report');

Route::post('/admin/salesordermarginaccountmappingsfilter', 'admin\SalesOrderMarginAccountMappingsController@filter');

//LoanProductAssets routes .....

Route::resource('admin/loanproductassets','admin\LoanProductAssetsController');

Route::get('/admin/loanproductassetsreport', 'admin\LoanProductAssetsController@report');

app/SalesOrderAccountMappings.php
<?php
/**
* @author  Wanjala Innocent Khaemba
*Model - (sales order account mappings)
*/
namespace App;
use Illuminate\Database\Eloquent\Model;
class SalesOrderAccountMappings extends Model
{
	public function productmodel(){
		return $this->belongsTo(Products::class, 'product');
	}
	public function paymentmodemodel(){
		return $this->belongsTo(PaymentModes::class, 'payment_mode');
	}
	public function debitaccountmodel(){
		return $this->belongsTo(Accounts::class, 'debit_account');
	}
	public function creditaccountmodel(){
		return $this->belongsTo(Accounts::class, 'credit_account');
	}
}

resources/views/admin/sales_order_account_mappings/create.blade.php
@extends("admin.home")
@section("main_content")
<div id="content" class="content">
    <ol class="breadcrumb pull-right">
        <li><a href="#">Home</a></li>
        <li><a href="#">public</a></li>
        <li><a href="#">Sales Order Account Mappings</a></li>
        <li class="active">form</li>
    </ol>
    <h1 class="page-header">Sales Order Account Mappings Form <small>sales order account mappings details goes here...</small></h1>
    <div class="row">
        <div class="col-md-12">
            <a href="{!! route('salesorderaccountmappings.index') !!}"><button type="button" class="btn btn-inverse btn-icon btn-circle m-b-10"><i class="fa fa-arrow-left"></i></button></a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-inverse">
                <div class="panel-heading">
                    <div class="panel-heading-btn">
                        <a href="#" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                        <a href="#" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
                        <a href="#" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                        <a href="#" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                    </div>
                    <h4 class="panel-title">DataForm - Autofill</h4>
                </div>
                <div class="panel-body">
                    <form id="form"  class="form-horizontal" enctype="multipart/form-data">
                        {!! csrf_field() !!}
                                <div class="form-group">
                                    <label for="Product" class="col-sm-3 control-label">Product</label>
                                    <div class="col-sm-6">
									    <select class="form-control selectpicker" data-size="100000" data-live-search="true" data-style="btn-white" name="product"  id="product">
                                            <option value="" >Select Product</option>				                                @foreach ($salesorderaccountmappingsdata['products'] as $products)
				                                <option value="{!! $products->id !!}">
					
				                                {!! $products->product_number!!}
				                                {!! $products->name!!}
				                                </option>
				                                @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="Payment Mode" class="col-sm-3 control-label">Payment Mode</label>
                                    <div class="col-sm-6">
									    <select class="form-control selectpicker" data-size="100000" data-live-search="true" data-style="btn-white" name="payment_mode"  id="payment_mode">
                                            <option value="" >Select Payment Mode</option>				                                @foreach ($salesorderaccountmappingsdata['paymentmodes'] as $paymentmodes)
				                                <option value="{!! $paymentmodes->id !!}">
					
				                                {!! $paymentmodes->name!!}
				                                </option>
				                                @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="Debit Account" class="col-sm-3 control-label">Debit Account</label>
                                    <div class="col-sm-6">
									    <select class="form-control selectpicker" data-size="100000" data-live-search="true" data-style="btn-white" name="debit_account"  id="debit_account">
                                            <option value="" >Select Debit Account</option>				                                @foreach ($salesorderaccountmappingsdata['accounts'] as $accounts)
				                                <option value="{!! $accounts->id !!}">
					
				                                {!! $accounts->code!!}
				                                {!! $accounts->name!!}
				                                </option>
				                                @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="Credit Account" class="col-sm-3 control-label">Credit Account</label>
                                    <div class="col-sm-6">
									    <select class="form-control selectpicker" data-size="100000" data-live-search="true" data-style="btn-white" name="credit_account"  id="credit_account">
                                            <option value="" >Select Credit Account</option>				                                @foreach ($salesorderaccountmappingsdata['accounts'] as $accounts)
				                                <option value="{!! $accounts->id !!}">
					
				                                {!! $accounts->code!!}
				                                {!! $accounts->name!!}
				                                </option>
				                                @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-sm-offset-3 col-sm-6">
                                        <button type="button" onclick="save()" class="btn btn-sm btn-primary" id="btn-save">
                                            <i class="fa fa-btn fa-plus"></i> Add Sales Order Account Mappings
                                        </button>
                                    </div>
                                </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script language="javascript" type="text/javascript">
function save(){
	$("#btn-save").attr("disable",true);
	var formData = new FormData($('#form')[0]);
	$.ajax({
		type:'POST',
		url: "{!! route('salesorderaccountmappings.store')!!}",
		data:formData,
		cache:false,
		contentType: false,
		processData: false,
		success:function(data){
		$("#btn-save").attr("disable",false);
			var obj = jQuery.parseJSON( data );
			if(obj.status=='1'){
				$.gritter.add({
					title: 'Success',
					text: obj.message,
					sticky: false,
					time: '1000',
				});
				$("#form")[0].reset();
			}else{
				$.gritter.add({
					title: 'Fail',
					text: obj.message,
					sticky: false,
					time: '5000',
				});
			}
		},error: function(data){
console.log(data)
			$.gritter.add({
				title: 'Error',
				text: 'An Error occured. Please review your data then submit again!!',
				sticky: false,
				time: '5000',
			});
		}
	});
	return false;
}
</script>
@endsection
@section('script')
<script language="javascript" type="text/javascript">
</script>
@endsection

resources/views/admin/sales_order_account_mappings/index.blade.php
@extends("admin.home")
@section("main_content")
<style type="text/css">
	td div img{
		max-width: 64px;
	}
</style>
<div id="content" class="content">
    <ol class="breadcrumb pull-right">
        <li><a href="#">Home</a></li>
        <li><a href="#">Public</a></li>
        <li><a href="#">Sales Order Account Mappings</a></li>
        <li class="active">Table</li>
    </ol>
    <h1 class="page-header">Sales Order Account Mappings - DATA <small>sales order account mappings data goes here...</small></h1>
    <div class="row">
        <div class="col-md-12">
            @if($salesorderaccountmappingsdata['usersaccountsroles'][0]->_add==1)
            <a href="{!! route('salesorderaccountmappings.create') !!}"><button type="button" class="btn btn-inverse btn-icon btn-circle m-b-10"><i class="fa fa-plus"></i></button></a>
            @endif
            @if($salesorderaccountmappingsdata['usersaccountsroles'][0]->_report==1)
            <a href="{!! url('admin/salesorderaccountmappingsreport') !!}"><button type="button" class="btn btn-inverse btn-icon btn-circle m-b-10"><i class="fa fa-file-text-o"></i></button></a>
            @endif
            @if($salesorderaccountmappingsdata['usersaccountsroles'][0]->_report==1 || $salesorderaccountmappingsdata['usersaccountsroles'][0]->_list==1)
            <a href="#modal-dialog"  data-toggle="modal"><button type="button" class="btn btn-inverse btn-icon btn-circle m-b-10"><i class="fa fa-filter"></i></button></a>
            @endif
        </div>
    </div>
    @if($salesorderaccountmappingsdata['usersaccountsroles'][0]->_list==1)
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-inverse">
                <div class="panel-heading">
                    <div class="panel-heading-btn">
                        <a href="#" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                        <a href="#" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
                        <a href="#" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                        <a href="#" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                    </div>
                    <h4 class="panel-title">DataTable - Autofill</h4>
                </div>
                <div class="panel-body">
                    <table id="data-table" class="table table-striped table-bordered">
                        <thead>
                                    <tr>
                                        <th>Product</th>
                                        <th>Payment Mode</th>
                                        <th>Debit Account</th>
                                        <th>Credit Account</th>
                                        <th>Action</th>                                    </tr>
                        </thead>
                        <tbody>
                        @foreach ($salesorderaccountmappingsdata['list'] as $salesorderaccountmappings)
                            <tr>
                                <td class='table-text'><div>
                                	{!! $salesorderaccountmappings->productmodel->product_number !!}
                                	{!! $salesorderaccountmappings->productmodel->name !!}
                                </div></td>
                                <td class='table-text'><div>
                                	{!! $salesorderaccountmappings->paymentmodemodel->name !!}
                                </div></td>
                                <td class='table-text'><div>
                                	{!! $salesorderaccountmappings->debitaccountmodel->code !!}
                                	{!! $salesorderaccountmappings->debitaccountmodel->name !!}
                                </div></td>
                                <td class='table-text'><div>
                                	{!! $salesorderaccountmappings->creditaccountmodel->code !!}
                                	{!! $salesorderaccountmappings->creditaccountmodel->name !!}
                                </div></td>
                                <td>
                <form action="{!! route('salesorderaccountmappings.destroy',$salesorderaccountmappings->id) !!}" method="POST">
                                        @if($salesorderaccountmappingsdata['usersaccountsroles'][0]->_show==1)
                                        <a href="{!! route('salesorderaccountmappings.show',$salesorderaccountmappings->id) !!}" id='show-salesorderaccountmappings-{!! $salesorderaccountmappings->id !!}' class='btn btn-sm btn-circle btn-inverse'>
                                            <i class='fa fa-btn fa-eye'></i>
                                        </a>
                                        @endif
                                        @if($salesorderaccountmappingsdata['usersaccountsroles'][0]->_edit==1)
                                        <a href="{!! route('salesorderaccountmappings.edit',$salesorderaccountmappings->id) !!}" id='edit-salesorderaccountmappings-{!! $salesorderaccountmappings->id !!}' class='btn btn-sm btn-circle btn-warning'>
                                            <i class='fa fa-btn fa-edit'></i>
                                        </a>
                                        @endif
                                        @if($salesorderaccountmappingsdata['usersaccountsroles'][0]->_delete==1)
                                        <input type="hidden" name="_method" value="delete" />
                                        {!! csrf_field() !!}
                                        {!! method_field('DELETE') !!}
                                        <button type='submit' id='delete-salesorderaccountmappings-{!! $salesorderaccountmappings->id !!}' class='btn btn-sm btn-circle btn-danger'>
                                            <i class='fa fa-btn fa-trash'></i>
                                        </button>
                                        @endif
                </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
    @endif
<div class="modal fade modal-message" id="modal-dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">close</button>
                <h4 class="modal-title">Sales Order Account Mappings - Filter Dialog</h4>
            </div>
            <div class="modal-body">
    			<div class="row">
                    <div class="col-md-12">
                        <div class="panel panel-inverse">
                            <div class="panel-heading">
                                <div class="panel-heading-btn">
                                    <a href="#" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                                    <a href="#" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
                                    <a href="#" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                                    <a href="#" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                                </div>
                                <h4 class="panel-title">DataForm - Autofill</h4>
                            </div>
                            <div class="panel-body">
                    <form id="form"  class="form-horizontal" action="{!! url('admin/salesorderaccountmappingsfilter') !!}" method="POST">
                        {!! csrf_field() !!}
                                <div class="form-group">
                                    <label for="Product" class="col-sm-3 control-label">Product</label>
                                    <div class="col-sm-6">
									    <select class="form-control selectpicker" data-size="100000" data-live-search="true" data-style="btn-white" name="product"  id="product">
                                            <option value="" >Select Product</option>				                                @foreach ($salesorderaccountmappingsdata['products'] as $products)
				                                <option value="{!! $products->id !!}">
					
				                                {!! $products->code!!}
				                                {!! $products->name!!}
				                                </option>
				                                @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="Payment Mode" class="col-sm-3 control-label">Payment Mode</label>
                                    <div class="col-sm-6">
									    <select class="form-control selectpicker" data-size="100000" data-live-search="true" data-style="btn-white" name="payment_mode"  id="payment_mode">
                                            <option value="" >Select Payment Mode</option>				                                @foreach ($salesorderaccountmappingsdata['paymentmodes'] as $paymentmodes)
				                                <option value="{!! $paymentmodes->id !!}">
					
				                                {!! $paymentmodes->name!!}
				                                </option>
				                                @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="Debit Account" class="col-sm-3 control-label">Debit Account</label>
                                    <div class="col-sm-6">
									    <select class="form-control selectpicker" data-size="100000" data-live-search="true" data-style="btn-white" name="debit_account"  id="debit_account">
                                            <option value="" >Select Debit Account</option>				                                @foreach ($salesorderaccountmappingsdata['accounts'] as $accounts)
				                                <option value="{!! $accounts->id !!}">
					
				                                {!! $accounts->code!!}
				                                {!! $accounts->name!!}
				                                </option>
				                                @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="Credit Account" class="col-sm-3 control-label">Credit Account</label>
                                    <div class="col-sm-6">
									    <select class="form-control selectpicker" data-size="100000" data-live-search="true" data-style="btn-white" name="credit_account"  id="credit_account">
                                            <option value="" >Select Credit Account</option>				                                @foreach ($salesorderaccountmappingsdata['accounts'] as $accounts)
				                                <option value="{!! $accounts->id !!}">
					
				                                {!! $accounts->code!!}
				                                {!! $accounts->name!!}
				                                </option>
				                                @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-sm-offset-3 col-sm-6">
                                    <div class="col-sm-offset-3 col-sm-6">
                                        <button type="submit" class="btn btn-sm btn-inverse">
                                            <i class="fa fa-btn fa-search"></i> Search Sales Order Account Mappings
                                        </button>
                                    </div>
                                </div>
                    </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <a href="javascript:;" class="btn btn-sm btn-white" data-dismiss="modal">Close</a>
            </div>
        </div>
    </div>
</div>
@endsection
@section('script')
@endsection